# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFoot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
  # Pods for MyFoot
  pod 'Alamofire'
  pod 'DGElasticPullToRefresh'
  pod 'SnapSliderFilters'
  pod 'SwiftyCam'
  pod 'NVActivityIndicatorView'
  pod 'PureLayout', '~> 3.0.1'
  pod 'FBSDKLoginKit'
  pod 'FacebookLogin'
  pod 'LBTAComponents', '~> 0.1.9'
  pod 'SwiftyJSON'
  pod 'ActiveLabel'
  pod 'FoldingCell'
  pod 'XLPagerTabStrip', '~> 8.0'
  pod 'CollectionKit'
  pod 'TwitterKit'
  pod 'TesseractOCRiOS', '4.0.0'
  

end
