# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFoot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFoot
  pod 'Alamofire'
  pod 'DGElasticPullToRefresh'
  pod 'SnapSliderFilters'
  pod 'SwiftyCam'
  pod 'NVActivityIndicatorView'
  pod 'PureLayout', '~> 3.0.1'
  pod 'FBSDKLoginKit'
  pod 'FacebookLogin'
  pod 'LBTAComponents', '~> 0.1.9'
  pod 'SwiftyJSON'
  pod 'ActiveLabel'
  pod 'FoldingCell'
  pod 'XLPagerTabStrip', '~> 8.0'
  pod 'CollectionKit'
  pod 'TwitterKit'
  

end
